"""
src/lcsc/types.pyi

Stub file for the `types.py` file.
"""
__all__ = ["CatalogDetails", "BrandDetails", "PriceDetails", "Spec", "ProductDetails", "SearchResult", "SearchResults"]

class CatalogDetails: ...
class BrandDetails: ...
class PriceDetails: ...
class Spec: ...
class ProductDetails: ...
class SearchResult: ...
class SearchResults: ...